const ERRORS = {
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  WRONG_CREDENTIALS: 'WRONG_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND'
}

export default ERRORS
